### ISSUE TITLE
Implement camera tracking of the object.

### ISSUE THREAD

**Issue by TodNaz** [TodNaz/Tida#14]
You need to implement camera tracking of the object, in particular:
- [x] Tracking by the pointer to the vector of the object and entering into the calculation also its size, which should help in the movement of the object to the right and down, without crossing its body outside the window frame.
- [x] Function for tracking an instance from a scene.
- [x] Dependence of the camera on the current scene. Each scene has its own camera.

---

An example of using the camera:
1. Without Scene-Instance-Component system:
```d
Vector!float position = vec!float(32 ,32);
...
renderer.camera.bindObject(&position, vec!float(32, 32));
//                                            ^ [1]         ^ [2]
// [1]: Pointer to the position of the object.
// [2]: The size of the object (the object is represented as a rectangle).
```
2. With Scene-Instance-Component system:
```d
class Main : Scene
{
    this() @safe
    {
        Instance player = new Instance();
        player.mask = Shape!float.Circle(vecf(32, 32), 8);
        player.position = vec!float(32, 32);

        this.camera.bindObject(player);
        // From the shape of the instance, the camera should calculate its representation as a rectangle.
    }
}
```

Directly, the tracking process should be in the `Camera.followObject()` function.

**Comment by TodNaz** [comment]
c7e4214
